---
- name: Patch Linux servers with sudo
  hosts: web
  become: yes          
  become_method: sudo  
  gather_facts: yes

  tasks:
    - name: Update all installed packages
      yum:
        name: "*"
        state: latest
...
